#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICES
#=================================================
ynh_script_progression "Stopping and removing the systemd services..."

ynh_config_remove_systemd
ynh_config_remove_systemd "$app-mint-session"

if yunohost service status "$app" >/dev/null 2>&1; then
	yunohost service remove "$app"
fi
if yunohost service status "$app-mint-session" >/dev/null 2>&1; then
	yunohost service remove "$app-mint-session"
fi

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx configuration..."

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
