#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR AND DATA DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
ynh_restore "$data_dir"

#=================================================
# RECREATE THE PYTHON VIRTUAL ENVIRONMENT
#=================================================
ynh_script_progression "Reinstalling the Python virtual environment..."

nostr_auth_install_venv

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="Nostr authentication add-on for YunoHost"

#=================================================
# START APP
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" \
	--log_path="systemd" \
	--wait_until="Uvicorn running on"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration of $app completed"
